#!/usr/bin/env node

/**
 * Build script to generate config.js from environment variables
 * This script runs during Vercel build to create config.js from Vercel environment variables
 */

const fs = require('fs');
const path = require('path');

// Get environment variables (Vercel will provide these)
// Vercel environment variables can be accessed directly via process.env
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

// Fallback to example values for local development (if env vars not set)
const config = {
    SUPABASE_URL: SUPABASE_URL || 'https://gkklkjoatvbxfekuyvnx.supabase.co',
    SUPABASE_ANON_KEY: SUPABASE_ANON_KEY || 'your-anon-key-here'
};

// Generate config.js content
const configContent = `// Supabase Configuration
// This file is auto-generated during build from environment variables
// DO NOT edit this file manually

const SUPABASE_CONFIG = {
    SUPABASE_URL: '${config.SUPABASE_URL}',
    SUPABASE_ANON_KEY: '${config.SUPABASE_ANON_KEY}'
};
`;

// Write config.js file
const configPath = path.join(__dirname, 'config.js');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✓ config.js generated successfully');
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.warn('⚠ Warning: Using fallback values. Make sure to set SUPABASE_URL and SUPABASE_ANON_KEY in Vercel environment variables.');
    console.warn('⚠ For local development, create config.js manually from config.example.js');
}

